apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app-deployment
spec:
  selector:
    matchLabels:
      app: echo-app
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-app
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: echo-app
        image: echo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
