apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default-inst
spec:
  exporter:
    endpoint: http://default-otel-collector.observability.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        value: "http://default-otel-collector.observability.svc.cluster.local:4318/v1/metrics"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.name=echo-app
